# Generated by Django 5.1.15 on 2026-05-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_cargar_carreras_iniciales'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilalumno',
            options={'ordering': ['matricula'], 'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfiles de usuarios'},
        ),
        migrations.AddField(
            model_name='perfilalumno',
            name='tipo',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('PROFESOR', 'Profesor')], default='ALUMNO', max_length=10),
        ),
        migrations.AlterField(
            model_name='perfilalumno',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='usuarios.carrera'),
        ),
    ]
